name: Refresh LinkedIn Cookies

on:
  schedule:
    # Run every Sunday at 9 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  refresh-cookies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies for Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium chromium-driver
        
    - name: Install Python dependencies
      run: |
        cd linkedin_scraper
        pip install -r requirements.txt
        pip install boto3
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Refresh LinkedIn cookies
      env:
        LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
        LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        JOBS_BUCKET: ${{ secrets.JOBS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        cd linkedin_scraper
        python3 refresh_cookies.py
        
    - name: Notify on success
      if: success()
      run: |
        echo "✅ LinkedIn cookies refreshed successfully!"
        echo "Next refresh scheduled for next Sunday at 9 AM UTC."
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ LinkedIn cookie refresh failed!"
        echo "Please check the logs and refresh manually if needed."